version: '3.8'

services:
   web:
     build: .
     container_name: carsharing
     command: bash entrypoint.sh
     ports:
       - "8000:8000"
     volumes:
       - .:/app
     depends_on:
       db:
         condition: service_healthy
     env_file:
       - .env
     environment:
       DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

   db:
     image: postgres:14
     container_name: postgres_db
     restart: always
     environment:
       POSTGRES_DB: ${DB_NAME:-megaautokg}
       POSTGRES_USER: ${DB_USER:-postgres}
       POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
     volumes:
       - postgres_data:/var/lib/postgresql/data
     healthcheck:
       test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-megaautokg}" ]
       interval: 5s
       timeout: 5s
       retries: 5

   redis:
     image: redis:7-alpine
     container_name: redis_server
     ports:
       - "6379:6379"
     volumes:
       - redis:/data

   worker:
     build: .
     container_name: celery_worker
     command: celery -A core worker -l info
     volumes:
       - .:/app
     depends_on:
       - db
       - redis
     env_file:
       - .env

volumes:
  postgres_data:
  redis: