# Generated by Django 5.2.4 on 2025-07-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марка машины', 'verbose_name_plural': 'Марки машины'},
        ),
        migrations.AlterModelOptions(
            name='carbrandtype',
            options={'verbose_name': 'Марка и тип машины'},
        ),
        migrations.AlterModelOptions(
            name='carstatushistory',
            options={'verbose_name': 'История статуса', 'verbose_name_plural': 'Истории статусов'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'verbose_name': 'Тип машины', 'verbose_name_plural': 'Типы машины'},
        ),
        migrations.AlterModelOptions(
            name='drivetype',
            options={'verbose_name': 'Тип привода'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Тип топлива'},
        ),
        migrations.AlterModelOptions(
            name='gearboxtype',
            options={'verbose_name': 'Коробка передачи'},
        ),
    ]
