# Generated by Django 5.2.4 on 2025-07-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_booking_status_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
